-- This UPDATES the Layout of an already deployed DB with Data.
-- USE WITH CARE, please backup DB before running this.

LOCK TABLES
    NetPivot.users WRITE,
    NetPivot.files WRITE,
    NetPivot.conversions WRITE,
    NetPivot.settings WRITE;

ALTER ONLINE TABLE NetPivot.conversions
    DROP FOREIGN KEY fk_conversions_users1,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.files
    DROP FOREIGN KEY fk_files_users,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.users
    MODIFY id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY max_files SMALLINT UNSIGNED NULL,
    MODIFY max_conversions SMALLINT UNSIGNED NULL,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.files
    MODIFY filename VARCHAR(255) NULL,
    MODIFY upload_time DATETIME(0) NULL,
    MODIFY users_id SMALLINT UNSIGNED NOT NULL,
    ADD CONSTRAINT fk_files_users
	FOREIGN KEY(users_id) REFERENCES NetPivot.users(id)
	ON DELETE CASCADE
	ON UPDATE NO ACTION,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.conversions
    MODIFY id_conversions SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY users_id SMALLINT UNSIGNED NOT NULL,
    MODIFY time_conversion DATETIME(0) NOT NULL,
    MODIFY converted_file VARCHAR(255) NOT NULL,
    MODIFY error_file VARCHAR(255) NULL,
    MODIFY stats_file VARCHAR(255) NULL,
    ADD CONSTRAINT fk_conversions_users1
	FOREIGN KEY(users_id) REFERENCES NetPivot.users(id)
	ON DELETE CASCADE
	ON UPDATE NO ACTION,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.settings
    MODIFY host_name TINYINT UNSIGNED NOT NULL,
    MODIFY files_path VARCHAR(255) NULL,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

UNLOCK TABLES;

DROP TABLE IF EXISTS NetPivot.stats CASCADE;
CREATE TABLE IF NOT EXISTS NetPivot.stats (
    files_uuid VARCHAR(36) NOT NULL UNIQUE PRIMARY KEY,
    char_total MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    char_conv MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    char_skip MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    mon_count MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    mon_chars MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    mon_lines MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    node_count MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    node_chars MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    node_lines MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    pools_count MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    pools_chars MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    pools_lines MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    virtual_count MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    virtual_chars MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    virtual_lines MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    vip_count MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    vip_chars MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    vip_lines MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    profile_count MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    profile_chars MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    profile_lines MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    persist_count MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    persist_chars MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    persist_lines MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT fk_stats_file1
        FOREIGN KEY(files_uuid) REFERENCES NetPivot.files(uuid)
        MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE = InnoDB;

