-- This UPDATES the Layout of an already deployed DB with Data.
-- USE WITH CARE, please backup DB before running this.

LOCK TABLES
    NetPivot.users WRITE,
    NetPivot.files WRITE,
    NetPivot.conversions WRITE,
    NetPivot.settings WRITE,
    NetPivot.stats WRITE;

ALTER ONLINE TABLE NetPivot.conversions
    DROP FOREIGN KEY fk_conversions_users1,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.files
    DROP FOREIGN KEY fk_files_users,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.stats
<<<<<<< HEAD
    DROP FOREIGN KEY fk_stats_files1,
=======
    DROP FOREIGN KEY fk_stats_file1,
>>>>>>> 9874dba4d8eb73de66befd9aa7fa2509563f8ace
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.users
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY max_files TINYINT UNSIGNED NULL,
    MODIFY max_conversions TINYINT UNSIGNED NULL,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.files
    MODIFY filename VARCHAR(255) NULL,
    MODIFY upload_time DATETIME(0) NULL,
    MODIFY users_id INT UNSIGNED NOT NULL,
    ADD CONSTRAINT fk_files_users
	FOREIGN KEY(users_id) REFERENCES NetPivot.users(id)
	ON DELETE CASCADE
	ON UPDATE NO ACTION,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.conversions
    MODIFY id_conversions BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY users_id INT UNSIGNED NOT NULL,
    MODIFY time_conversion DATETIME(0) NOT NULL,
    MODIFY converted_file VARCHAR(255) NOT NULL,
    MODIFY error_file VARCHAR(255) NULL,
    MODIFY stats_file VARCHAR(255) NULL,
    ADD CONSTRAINT fk_conversions_users1
	FOREIGN KEY(users_id) REFERENCES NetPivot.users(id)
	ON DELETE CASCADE
	ON UPDATE NO ACTION,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.settings
    MODIFY host_name TINYINT UNSIGNED NOT NULL,
    MODIFY files_path VARCHAR(255) NULL,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

ALTER ONLINE TABLE NetPivot.stats
    MODIFY files_uuid VARCHAR(36) NOT NULL,
    DROP char_conv,
    DROP char_skip,
    DROP node_count,
    DROP pools_count,
    DROP virtual_count,
    DROP vip_count,
    DROP profile_count,
    DROP persist_count,
    ADD cli_status BOOLEAN NOT NULL DEFAULT 0,
    ADD cli_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD cli_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD cli_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD auth_status BOOLEAN NOT NULL DEFAULT 0,
    ADD auth_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD auth_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD auth_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD apm_status BOOLEAN NOT NULL DEFAULT 0,
    ADD apm_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD apm_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD apm_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD cm_status BOOLEAN NOT NULL DEFAULT 0,
    ADD cm_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD cm_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD cm_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD gtm_status BOOLEAN NOT NULL DEFAULT 0,
    ADD gtm_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD gtm_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD gtm_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_mon_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_mon_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_mon_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_mon_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD irules_status BOOLEAN NOT NULL DEFAULT 0,
    ADD irules_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD irules_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD irules_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD mon_status BOOLEAN NOT NULL DEFAULT 0,
    ADD mon_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY mon_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY mon_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD nodes_status BOOLEAN NOT NULL DEFAULT 0,
    ADD nodes_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    CHANGE node_chars nodes_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    CHANGE node_lines nodes_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD pools_status BOOLEAN NOT NULL DEFAULT 0,
    ADD pools_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY pools_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY pools_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD virtuals_status BOOLEAN NOT NULL DEFAULT 0,
    ADD virtuals_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    CHANGE virtual_chars virtuals_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    CHANGE virtual_lines virtuals_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD vip_status BOOLEAN NOT NULL DEFAULT 0,
    ADD vip_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY vip_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY vip_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD prof_status BOOLEAN NOT NULL DEFAULT 0,
    ADD prof_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    CHANGE profile_chars prof_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    CHANGE profile_lines prof_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD pers_status BOOLEAN NOT NULL DEFAULT 0,
    ADD pers_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    CHANGE persist_chars pers_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    CHANGE persist_lines pers_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_auth_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_auth_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_auth_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_auth_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_snat_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_snat_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_snat_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_snat_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_snat_t_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_snat_t_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_snat_t_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_snat_t_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_snat_p_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_snat_p_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_snat_p_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_snat_p_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_class_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_class_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_class_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_class_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_data_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_data_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_data_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_data_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_global_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_global_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_global_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_global_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_pol_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_pol_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_pol_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_pol_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_pol_s_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ltm_pol_s_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_pol_s_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ltm_pol_s_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD net_status BOOLEAN NOT NULL DEFAULT 0,
    ADD net_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD net_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD net_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD pem_status BOOLEAN NOT NULL DEFAULT 0,
    ADD pem_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD pem_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD pem_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD security_status BOOLEAN NOT NULL DEFAULT 0,
    ADD security_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD security_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD security_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD sys_status BOOLEAN NOT NULL DEFAULT 0,
    ADD sys_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD sys_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD sys_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD wom_status BOOLEAN NOT NULL DEFAULT 0,
    ADD wom_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD wom_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD wom_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ignored_status BOOLEAN NOT NULL DEFAULT 0,
    ADD ignored_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ignored_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD ignored_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD total_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    CHANGE char_total total_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD total_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD total_p_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD total_p_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD total_p_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD total_s_obj SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD total_s_chars SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD total_s_lines SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD CONSTRAINT fk_stats_files1
	FOREIGN KEY(files_uuid) REFERENCES NetPivot.files(uuid)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
    ALGORITHM=DEFAULT,
    LOCK=EXCLUSIVE;

UNLOCK TABLES;
