<div class="modal fade delete_confirm_dialog" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button id="delete_confirm_close" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button> 
                <h4 class="modal-title" id="mySmallModalLabel">Confirmation</h4> 
            </div>
            <div class="modal-body">
                <h4>Are you sure you want to delete this quote?</h4>
                <p>Deleting this quote cannot be undone. By deleting this quote, you are also deleting all related objects like lines.</p>
                <br>
                <button id="deleteProject" class="btn btn-danger">Yes</button>
                <button id="delete_confirm_close" type="button" class="btn btn-success" data-dismiss="modal" aria-label="Close">No</button> 
            </div>
        </div>
    </div>
</div>