<div class="panel panel-default">
    <div class="panel-heading">
        <h4>File Upload</h4>
    </div>
    <div class="panel-body">
        <span class="btn btn-success fileinput-button">
            <span>Add file...</span>
            <input id="fileupload" type="file" name="InputFile">
        </span>
        <div id="progress" class="progress">
            <div class="progress-bar progress-bar-success"></div>
        </div>
        <div>
            <ul class="list-group" id="lp">
            </ul>
        </div>
    </div>
</div>
