<div class="col-xs-12 col-md-10 content">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>Hardware Compare</h4>
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <td>F5 Type</td>
                    <td>
                    <div class="dropdown">
                        <button class="btn btn-block dropdown-toggle" type="button" data-toggle="dropdown">
                            <span id="F5_selectedType">BigIP</span>
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" id="F5_types"></ul>
                    </div>
                    </td>
                </tr>
                <tr>
                    <td>F5 Model</td>
                    <td>
                    <div class="dropdown">
                        <button class="btn btn-block dropdown-toggle" type="button" data-toggle="dropdown">
                            <span id="npF5">Select Model</span>
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" id="F5_models"></ul>
                    </div>
                    </td>
                </tr>
                <tr>
                    <td>NetScaler Type</td>
                    <td>
                    <div class="dropdown">
                        <button class="btn btn-block dropdown-toggle" type="button" data-toggle="dropdown">
                            <span id="NetScaler_selectedType">MPX</span>
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" id="NetScaler_types"></ul>
                    </div>
                    </td>
                </tr>
                <tr>
                    <td>NetScaler Model</td>
                    <td>
                    <div class="dropdown">
                        
                        <button class="btn btn-block dropdown-toggle" type="button" data-toggle="dropdown">
                            <span id="npNetScaler">Select Model</span>
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" id="NetScaler_models"></ul>
                    </div>
                    </td>
                </tr>
            </table>
            <div id="compare"></div>
        </div>
    </div>
</div>
