<div class="panel panel-default">
    <div class="panel-heading">
        <h4>NginX Plus Conversion</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-12 col-md-12 content">
                The conversion tool for Nginx Plus does not keep track of converted files. For now it only generates the converted file and output for download.
            </div>
        </div>
        <div class="row">&nbsp;</div>
        <div class="row">
            <div class="col-md-4">
                <button type="button" class="btn btn-success" id="btn_fileupload" >Upload File</button>
            </div>
            <div class="col-md-4 result hidden">
                <a id="btn_nsdownload" class="btn btn-primary result">Download NS config file</a>
            </div>
            <div class="col-md-4 result hidden">
                <a id="btn_errorout" class="btn btn-warning result">Download conversion output</a>
            </div>
        </div>
    </div>
</div>